- name: Fast FTP
  # You may pin to the exact commit or the version.
  # uses: anvil-solutions/Fast-FTP-Action@de62eeaf1c409a96c7304f3bba8bf8194d0fa98f
  uses: anvil-solutions/Fast-FTP-Action@2.1.3
  with:
    # FTP server name (you may need to specify a port)
    server: sl1011.web.hostpoint.ch
    # FTP account username
    username: git@flawas.ch
    # FTP account password
    password: j*tDWDkGNk!!FvMepJDh
    # Protocol used to deploy (ftp or sftp)
    method: # optional, default is ftp
    # The local folder to copy, defaults to root project folder
    local_dir: # optional, default is .
    # The remote folder to copy to, deafults to root FTP folder
    remote_dir: # optional, default is .
